on:
    push:
      branches: [ main ]
     
jobs: 

 PowerShellDemo:
    name: "PowerShell Demo"
    runs-on: ubuntu-latest
    steps:
          - name: Login via Az module
            uses: azure/login@v1
            with:
             creds: ${{secrets.AZURE_CREDENTIALS}}
             enable-AzPSSession: true

          - name: Build Module
            shell: pwsh
            run: 
              Install-Module -Name Az -Repository PSGallery -Force
              ./rg.ps1 -Task ModuleBuild
           
    
     
